"""Enterprise Invoice & Billing Engine (Point 19) + Tax/GST (Point 18).

Invoices are auto-generated when an order is delivered (idempotent), stored permanently,
and can be regenerated by admin. Each invoice contains:
  - Legally-required company details (from business_rules: gst_number, pan, address)
  - Line items with per-item GST split (CGST + SGST or IGST)
  - Delivery charge (typically GST-free)
  - Grand total

GST calc uses per-product `gst_percentage` (default = business_rules.default_gst_percentage).
"""
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query

from audit import log_event
from auth import get_current_user
from db import get_db
from models import new_id, utcnow
from rbac import require_permission

router = APIRouter(tags=["invoices"])


def _next_invoice_number(now: datetime, seq: int) -> str:
    """NEDS-YYYY-MM-#### format (padded 4-digit seq per month)."""
    return f"NEDS-{now.strftime('%Y-%m')}-{seq:04d}"


async def _compute_invoice(db, order: dict) -> dict:
    """Given an order doc, compute the full invoice payload (does NOT insert)."""
    rules = await db.business_rules.find_one({"id": "default"}, {"_id": 0}) or {}

    company = {
        "name": rules.get("platform_name") or "NEDS STORE",
        "gst_number": rules.get("company_gst_number") or None,
        "pan": rules.get("company_pan") or None,
        "address": rules.get("company_address") or "",
        "state": rules.get("company_state") or "",
        "state_code": rules.get("company_state_code") or "",
    }
    gst_enabled = bool(rules.get("gst_enabled", True))
    default_gst_pct = float(rules.get("default_gst_percentage", 18.0))

    # Customer (buyer) details
    buyer = await db.users.find_one({"id": order["customer_id"]}, {"_id": 0, "name": 1, "mobile": 1, "email": 1, "address": 1})
    buyer_info = {
        "name": (buyer or {}).get("name", "Customer"),
        "mobile": (buyer or {}).get("mobile", ""),
        "email": (buyer or {}).get("email", ""),
        "address": order.get("delivery_address", ""),
        "state_code": rules.get("company_state_code") or "",  # simplified: assume same-state
    }

    # Product GST lookup
    product_ids = [it.get("product_id") for it in order.get("items", []) if it.get("product_id")]
    gst_lookup: dict[str, dict] = {}
    async for p in db.products.find(
        {"id": {"$in": product_ids}},
        {"_id": 0, "id": 1, "gst_percentage": 1, "hsn_code": 1},
    ):
        gst_lookup[p["id"]] = {
            "gst_percentage": float(p.get("gst_percentage") if p.get("gst_percentage") is not None else default_gst_pct),
            "hsn_code": p.get("hsn_code") or "",
        }

    same_state = (buyer_info["state_code"] or "") == (company["state_code"] or "")

    lines: list[dict] = []
    total_taxable = 0.0
    total_cgst = 0.0
    total_sgst = 0.0
    total_igst = 0.0

    for it in order.get("items", []):
        pid = it.get("product_id")
        gst_info = gst_lookup.get(pid, {"gst_percentage": default_gst_pct, "hsn_code": ""})
        qty = int(it.get("qty", 0))
        price = float(it.get("price", 0))
        line_total_inc = round(price * qty, 2)  # treat product price as GST-inclusive (Indian retail convention)
        gst_pct = float(gst_info["gst_percentage"]) if gst_enabled else 0.0

        # Reverse-calc taxable amount from inclusive price
        if gst_pct > 0:
            taxable = round(line_total_inc / (1 + gst_pct / 100), 2)
        else:
            taxable = line_total_inc
        gst_amount = round(line_total_inc - taxable, 2)

        if same_state:
            cgst = round(gst_amount / 2, 2)
            sgst = round(gst_amount - cgst, 2)
            igst = 0.0
        else:
            cgst = 0.0
            sgst = 0.0
            igst = gst_amount

        lines.append({
            "product_id": pid,
            "name": it.get("name"),
            "hsn_code": gst_info["hsn_code"],
            "qty": qty,
            "unit_price_inclusive": price,
            "taxable_amount": taxable,
            "gst_percentage": gst_pct,
            "cgst": cgst,
            "sgst": sgst,
            "igst": igst,
            "line_total": line_total_inc,
        })
        total_taxable += taxable
        total_cgst += cgst
        total_sgst += sgst
        total_igst += igst

    delivery_charge = float(order.get("delivery_charge", 0))
    grand_total = round(total_taxable + total_cgst + total_sgst + total_igst + delivery_charge, 2)

    return {
        "company": company,
        "buyer": buyer_info,
        "lines": lines,
        "subtotal_taxable": round(total_taxable, 2),
        "total_cgst": round(total_cgst, 2),
        "total_sgst": round(total_sgst, 2),
        "total_igst": round(total_igst, 2),
        "total_gst": round(total_cgst + total_sgst + total_igst, 2),
        "delivery_charge": delivery_charge,
        "grand_total": grand_total,
        "gst_enabled": gst_enabled,
        "same_state": same_state,
    }


async def generate_invoice_for_order(db, order: dict, actor: dict | None = None, force: bool = False) -> dict:
    """Idempotently generate an invoice for a delivered order. Returns the invoice doc."""
    if not force:
        existing = await db.invoices.find_one({"order_id": order["id"]}, {"_id": 0})
        if existing:
            return existing

    now = utcnow()
    # Sequence per month
    month_prefix = now.strftime("%Y-%m")
    monthly_count = await db.invoices.count_documents({"invoice_month": month_prefix})
    invoice_number = _next_invoice_number(now, monthly_count + 1)

    computed = await _compute_invoice(db, order)

    doc = {
        "id": new_id(),
        "invoice_number": invoice_number,
        "invoice_month": month_prefix,
        "order_id": order["id"],
        "customer_id": order.get("customer_id"),
        "issued_at": now,
        "status": "issued",
        "cancelled_at": None,
        "payment_method": order.get("payment_method"),
        "payment_status": order.get("payment_status"),
        **computed,
    }

    if force:
        await db.invoices.delete_many({"order_id": order["id"]})
    await db.invoices.insert_one(doc)
    doc.pop("_id", None)
    await log_event(actor, "invoice.generate", "invoice", doc["id"], {"invoice_number": invoice_number, "order_id": order["id"]})
    return doc


# ============ ROUTES ============
@router.get("/invoices")
async def list_invoices(
    status: str | None = None,
    q: str | None = None,
    limit: int = Query(200, le=500),
    _: dict = Depends(require_permission("invoices.view")),
):
    db = get_db()
    filt: dict = {}
    if status: filt["status"] = status
    if q: filt["invoice_number"] = {"$regex": q, "$options": "i"}
    cursor = db.invoices.find(filt, {"_id": 0}).sort("issued_at", -1).limit(limit)
    items = await cursor.to_list(limit)
    return {"items": items, "total": await db.invoices.count_documents(filt)}


@router.get("/invoices/summary")
async def invoices_summary(_: dict = Depends(require_permission("invoices.view"))):
    db = get_db()
    total = await db.invoices.count_documents({})
    cancelled = await db.invoices.count_documents({"status": "cancelled"})
    agg = await db.invoices.aggregate([
        {"$match": {"status": "issued"}},
        {"$group": {
            "_id": None,
            "gross": {"$sum": "$grand_total"},
            "gst": {"$sum": "$total_gst"},
        }},
    ]).to_list(1)
    return {
        "total_invoices": total,
        "cancelled_invoices": cancelled,
        "gross_billing": round(agg[0]["gross"], 2) if agg else 0,
        "total_gst_collected": round(agg[0]["gst"], 2) if agg else 0,
    }


@router.get("/invoices/{invoice_id}")
async def get_invoice(invoice_id: str, _: dict = Depends(require_permission("invoices.view"))):
    db = get_db()
    # Support both by id and by invoice_number
    inv = await db.invoices.find_one(
        {"$or": [{"id": invoice_id}, {"invoice_number": invoice_id}]},
        {"_id": 0},
    )
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    return inv


@router.post("/invoices/generate/{order_id}", status_code=201)
async def generate_invoice(order_id: str, current_user: dict = Depends(require_permission("invoices.regenerate"))):
    db = get_db()
    order = await db.orders.find_one({"id": order_id}, {"_id": 0})
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    if order.get("status") not in ("delivered",):
        raise HTTPException(status_code=400, detail="Invoices can only be generated for delivered orders")
    inv = await generate_invoice_for_order(db, order, actor=current_user, force=False)
    return inv


@router.post("/invoices/{invoice_id}/regenerate")
async def regenerate_invoice(invoice_id: str, current_user: dict = Depends(require_permission("invoices.regenerate"))):
    db = get_db()
    inv = await db.invoices.find_one({"id": invoice_id}, {"_id": 0})
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    order = await db.orders.find_one({"id": inv["order_id"]}, {"_id": 0})
    if not order:
        raise HTTPException(status_code=404, detail="Underlying order not found")
    new_inv = await generate_invoice_for_order(db, order, actor=current_user, force=True)
    return new_inv


@router.post("/invoices/{invoice_id}/cancel")
async def cancel_invoice(invoice_id: str, current_user: dict = Depends(require_permission("invoices.regenerate"))):
    db = get_db()
    inv = await db.invoices.find_one({"id": invoice_id})
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    now = utcnow()
    await db.invoices.update_one(
        {"id": invoice_id},
        {"$set": {"status": "cancelled", "cancelled_at": now, "cancelled_by": current_user["id"]}},
    )
    await log_event(current_user, "invoice.cancel", "invoice", invoice_id, {"invoice_number": inv.get("invoice_number")})
    return {"ok": True}
