import React from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { PublicHeader } from "@/src/components/PublicHeader";
import { useCart } from "@/src/context/CartContext";
import { theme, inr } from "@/src/theme";

export default function CartPage() {
  const router = useRouter();
  const { items, subtotal, updateQty, removeItem, clearCart } = useCart();
  return <View style={styles.page}><PublicHeader /><ScrollView contentContainerStyle={styles.scroll}><View style={styles.content}>
    <View style={styles.head}><Text style={styles.title}>Your Cart</Text><Text style={styles.sub}>{items.length} item{items.length === 1 ? "" : "s"}</Text></View>
    {!items.length ? <View style={styles.empty}><Feather name="shopping-cart" size={44} color={theme.colors.textSubtle} /><Text style={styles.emptyTitle}>Your cart is empty</Text><Text style={styles.sub}>Add products from the NEDS STORE catalogue.</Text><Pressable style={styles.primary} onPress={() => router.push("/products" as any)}><Text style={styles.primaryText}>Browse Products</Text></Pressable></View> : <View style={styles.layout}>
      <View style={styles.items}>{items.map((item) => <View key={item.product_id} style={styles.item}><View style={styles.itemImage}>{item.image_base64 ? <Image source={{ uri: item.image_base64 }} style={styles.image} /> : <Feather name="package" size={28} color={theme.colors.primary} />}</View><View style={styles.itemMain}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.price}>{inr(item.price)}</Text><View style={styles.controls}><Pressable onPress={() => updateQty(item.product_id, item.qty - 1)} style={styles.qty}><Text style={styles.qtyText}>−</Text></Pressable><Text style={styles.qtyValue}>{item.qty}</Text><Pressable onPress={() => updateQty(item.product_id, item.qty + 1)} style={styles.qty}><Text style={styles.qtyText}>+</Text></Pressable><Pressable onPress={() => removeItem(item.product_id)} style={styles.remove}><Text style={styles.removeText}>Remove</Text></Pressable></View></View><Text style={styles.lineTotal}>{inr(item.price * item.qty)}</Text></View>)}<Pressable onPress={clearCart} style={styles.clear}><Text style={styles.clearText}>Clear cart</Text></Pressable></View>
      <View style={styles.summary}><Text style={styles.summaryTitle}>Order Summary</Text><View style={styles.row}><Text style={styles.label}>Subtotal</Text><Text style={styles.value}>{inr(subtotal)}</Text></View><View style={styles.row}><Text style={styles.label}>Delivery</Text><Text style={styles.muted}>Calculated at checkout</Text></View><View style={styles.divider} /><View style={styles.row}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>{inr(subtotal)}</Text></View><Pressable onPress={() => router.push("/checkout" as any)} style={styles.primary}><Text style={styles.primaryText}>Proceed to Checkout</Text><Feather name="arrow-right" size={16} color="#fff" /></Pressable></View>
    </View>}
  </View></ScrollView></View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FAFAF8" }, scroll: { paddingBottom: 48 }, content: { width: "100%", maxWidth: 1200, alignSelf: "center", paddingHorizontal: 16 }, head: { paddingTop: 28, paddingBottom: 18 }, title: { fontSize: 28, fontWeight: "900", color: theme.colors.text }, sub: { marginTop: 4, color: theme.colors.textMuted, fontSize: 13 }, layout: { flexDirection: "row", gap: 18, flexWrap: "wrap", alignItems: "flex-start" }, items: { flex: 1, minWidth: 320 }, item: { flexDirection: "row", gap: 14, alignItems: "center", padding: 14, backgroundColor: "#fff", borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, marginBottom: 10 }, itemImage: { width: 82, height: 82, borderRadius: 9, backgroundColor: "#FAFAFA", alignItems: "center", justifyContent: "center", overflow: "hidden" }, image: { width: "100%", height: "100%" }, itemMain: { flex: 1 }, itemName: { fontSize: 14, fontWeight: "800", color: theme.colors.text }, price: { marginTop: 5, fontSize: 14, fontWeight: "800", color: theme.colors.text }, controls: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 10 }, qty: { width: 28, height: 28, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 6, alignItems: "center", justifyContent: "center" }, qtyText: { fontSize: 17, color: theme.colors.text }, qtyValue: { minWidth: 18, textAlign: "center", fontWeight: "800" }, remove: { marginLeft: 6 }, removeText: { color: theme.colors.danger, fontSize: 11, fontWeight: "700" }, lineTotal: { fontSize: 15, fontWeight: "900", color: theme.colors.text }, summary: { width: 340, maxWidth: "100%", padding: 18, backgroundColor: "#fff", borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14 }, summaryTitle: { fontSize: 18, fontWeight: "900", color: theme.colors.text, marginBottom: 18 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10, marginBottom: 12 }, label: { color: theme.colors.textMuted, fontSize: 13 }, value: { color: theme.colors.text, fontWeight: "800" }, muted: { color: theme.colors.textSubtle, fontSize: 11 }, divider: { height: 1, backgroundColor: theme.colors.border, marginVertical: 8 }, totalLabel: { color: theme.colors.text, fontWeight: "900", fontSize: 15 }, total: { color: theme.colors.text, fontWeight: "900", fontSize: 19 }, primary: { marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingVertical: 12, borderRadius: 8, backgroundColor: theme.colors.primary }, primaryText: { color: "#fff", fontWeight: "800" }, clear: { alignSelf: "flex-end", padding: 8 }, clearText: { color: theme.colors.danger, fontSize: 12, fontWeight: "700" }, empty: { minHeight: 400, alignItems: "center", justifyContent: "center", gap: 8 }, emptyTitle: { fontSize: 20, fontWeight: "900", color: theme.colors.text } });
