import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Feather } from "@expo/vector-icons";
import { useAuth, isAdminRole } from "@/src/context/AuthContext";
import { theme } from "@/src/theme";

const roleInfo:any={customer:{title:"Customer",subtitle:"Shop products and manage your orders",items:["Browse Store","Cart & Checkout","My Orders"]},seller:{title:"Seller",subtitle:"Manage your store, products and orders",items:["Products","Inventory","Orders","Settlements"]},rider:{title:"Rider",subtitle:"Manage assigned deliveries and earnings",items:["Assigned Deliveries","Delivery History","Earnings"]},staff:{title:"Staff",subtitle:"Operations workspace",items:["Orders","Customers","Support"]},staff_admin:{title:"Staff Admin",subtitle:"Operations and team management",items:["Dashboard","Orders","Staff","Reports"]},manager:{title:"Manager",subtitle:"Business operations dashboard",items:["Dashboard","Orders","Inventory","Reports"]}};
export default function RoleHome(){const {user,logout}=useAuth();const router=useRouter();if(!user)return null;const info=roleInfo[user.role]||roleInfo.customer;return <ScrollView contentContainerStyle={s.page}><View style={s.brand}><Text style={s.brandText}>NEDS SUPER STORE</Text><Text style={s.tag}>Learn • Grow • Succeed</Text></View><View style={s.card}><Text style={s.welcome}>Welcome, {user.name}</Text><Text style={s.role}>{info.title}</Text><Text style={s.sub}>{info.subtitle}</Text><View style={s.grid}>{info.items.map((x:string,i:number)=><View key={x} style={s.tile}><Feather name={i%2?"list":"grid"} size={22} color={theme.colors.primary}/><Text style={s.tileText}>{x}</Text></View>)}</View>{user.role==="customer"&&<Pressable style={s.primary} onPress={()=>router.push("/store")}><Text style={s.primaryText}>Open Store</Text></Pressable>}{isAdminRole(user.role)&&<Pressable style={s.primary} onPress={()=>router.push("/admin/dashboard")}><Text style={s.primaryText}>Open Admin Panel</Text></Pressable>}<Pressable style={s.outline} onPress={logout}><Text style={s.outlineText}>Sign Out</Text></Pressable></View></ScrollView>}
const s=StyleSheet.create({page:{flexGrow:1,backgroundColor:"#f4f4f5",padding:20,justifyContent:"center"},brand:{alignItems:"center",marginBottom:20},brandText:{fontSize:24,fontWeight:"900",color:theme.colors.surface},tag:{fontSize:11,color:theme.colors.primary,fontWeight:"700",marginTop:4},card:{backgroundColor:"#fff",borderRadius:16,padding:22,width:"100%",maxWidth:620,alignSelf:"center",borderWidth:1,borderColor:theme.colors.border},welcome:{fontSize:22,fontWeight:"800",color:theme.colors.text},role:{fontSize:15,fontWeight:"700",color:theme.colors.primary,marginTop:5},sub:{fontSize:13,color:theme.colors.textMuted,marginTop:4},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:20},tile:{width:"48%",minHeight:82,borderWidth:1,borderColor:theme.colors.border,borderRadius:10,padding:14,justifyContent:"center",gap:8},tileText:{fontSize:13,fontWeight:"700",color:theme.colors.text},primary:{marginTop:20,backgroundColor:theme.colors.primary,borderRadius:9,padding:13,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"800"},outline:{marginTop:10,borderWidth:1,borderColor:theme.colors.border,borderRadius:9,padding:12,alignItems:"center"},outlineText:{color:theme.colors.text,fontWeight:"700"}});
