import React,{useEffect,useState} from "react";
import {KeyboardAvoidingView,Platform,StyleSheet,Text,View} from "react-native";
import {useRouter} from "expo-router";
import {Button} from "@/src/components/Button";
import {Input} from "@/src/components/Input";
import {useAuth,isAdminRole} from "@/src/context/AuthContext";
import {useToast} from "@/src/components/Toast";
import {theme} from "@/src/theme";
export default function SignIn(){const {login,user,loading}=useAuth();const router=useRouter();const toast=useToast();const [mobile,setMobile]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>{if(!loading&&user) router.replace(isAdminRole(user.role)?"/admin/dashboard":"/role-home");},[loading,user,router]);const submit=async()=>{if(!/^\d{10}$/.test(mobile)||password.length<4){toast.error("Enter valid mobile number and password");return;}setBusy(true);try{const u=await login(mobile,password);toast.success(`Welcome, ${u.name}`);router.replace(isAdminRole(u.role)?"/admin/dashboard":"/role-home");}catch(e:any){toast.error(e.message||"Login failed");}finally{setBusy(false);}};return <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={s.root}><View style={s.card}><View style={s.logo}><Text style={s.logoText}>N</Text></View><Text style={s.title}>NEDS SUPER STORE</Text><Text style={s.sub}>Partner & Team Login</Text><Input label="Mobile Number" value={mobile} onChangeText={v=>setMobile(v.replace(/\D/g,"").slice(0,10))} keyboardType="number-pad" maxLength={10} placeholder="10-digit mobile"/><View style={{height:14}}/><Input label="Password" value={password} onChangeText={setPassword} secureTextEntry placeholder="Password"/><View style={{height:18}}/><Button title={busy?"Signing in…":"Sign In"} loading={busy} onPress={submit} fullWidth/><Text style={s.note}>Customer shopping is available without login. Admin, seller, rider and staff accounts use this secure sign-in.</Text></View></KeyboardAvoidingView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f4f4f5",justifyContent:"center",alignItems:"center",padding:20},card:{width:"100%",maxWidth:430,backgroundColor:"#fff",padding:26,borderRadius:16,borderWidth:1,borderColor:theme.colors.border},logo:{width:54,height:54,borderRadius:12,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center",marginBottom:14},logoText:{fontSize:27,fontWeight:"900",color:"#fff"},title:{fontSize:24,fontWeight:"900",color:theme.colors.text},sub:{fontSize:13,color:theme.colors.textMuted,marginTop:3,marginBottom:22},note:{fontSize:11,color:theme.colors.textMuted,lineHeight:17,marginTop:16,textAlign:"center"}});
